// src/components/Filter.tsx
import { useStore } from "@nanostores/react";
import { $map } from "../store/map";
import "./Filter.css";
import { useEffect, useState } from "react";
import type { Category } from "../utils/category";

export const Filter = () => {
  const [selectedCategories, setSelectedCategories] = useState<Category[]>([]);

  const map = useStore($map);

  const isSelected = (kind: Category) => selectedCategories.includes(kind);

  const toggleCategory = (kind: Category) => {
    if (isSelected(kind)) {
      setSelectedCategories([]);
    } else {
      setSelectedCategories([kind]);
    }
  };

  useEffect(() => {
    if (map) {
      const mapStyle = map.getStyle();

      if (selectedCategories.length === 0) {
        // show all
        (mapStyle.sources.features as any).filter = null;
      } else {
        (mapStyle.sources.features as any).filter = [
          "in",
          ["get", "fivh:category"],
          ["literal", selectedCategories],
        ];
      }
      map.setStyle(mapStyle);
    }
  }, [selectedCategories, map]);

  return (
    <div className="filter-container">
      <button
        className={
          isSelected("Gjenbruk")
            ? "filter-button filter-button-selected"
            : "filter-button"
        }
        onClick={() => toggleCategory("Gjenbruk")}
      >
        Gjenbruk
      </button>
      <button
        className={
          isSelected("Reparasjon")
            ? "filter-button filter-button-selected"
            : "filter-button"
        }
        onClick={() => toggleCategory("Reparasjon")}
      >
        Reparasjon
      </button>
      <button
        className={
          isSelected("Utlån")
            ? "filter-button filter-button-selected"
            : "filter-button"
        }
        onClick={() => toggleCategory("Utlån")}
      >
        Utlån
      </button>
    </div>
  );
};

// src/components/Filter.svelte
<script lang="ts">
  import { selectedCategories } from "../store/filter";
  import { map } from "../store/map";
  import { categories, type CategoryName } from "../utils/category";

  function toggleCategory(kind: CategoryName) {
    selectedCategories.update((current) => {
      if (current.includes(kind)) {
        return [];
      }
      return [kind];
    });
  }

  $: if ($map?.isStyleLoaded()) {
    const mapStyle = $map.getStyle();
    const featuresSource = (mapStyle.sources as any)?.features;

    if (featuresSource) {
      if ($selectedCategories.length === 0) {
        featuresSource.filter = null;
      } else {
        featuresSource.filter = [
          "in",
          ["get", "fivh:category"],
          ["literal", $selectedCategories],
        ];
      }

      $map.setStyle(mapStyle);
    }
  }
</script>

<div class="filter-container">
  {#each categories as c (c.name)}
    <button
      class="filter-button"
      class:filter-button-selected={$selectedCategories.includes(c.name)}
      onclick={() => toggleCategory(c.name)}
    >
      {c.label}
    </button>
  {/each}
</div>

<style>
  .filter-container {
    position: fixed;
    display: flex;
    top: 4rem;
    left: 1rem;
    gap: 0.5rem;
  }

  .filter-button {
    font-size: 1.2rem;
    border-radius: 0.5rem;
    background-color: #ffffff;
    color: black;
    width: fit-content;
    padding: 0.5rem;
    border: none;
    cursor: pointer;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    font-family: inherit;
  }

  .filter-button-selected {
    background-color: #ff7a00;
    color: white;
  }
</style>
